import crypto from 'node:crypto';
import { json, body, options } from '../lib/http.js';
import { geminiText, parseJsonLoose } from '../lib/gemini.js';
import { tokenFromBlob, getTree, getFile, commitFiles } from '../lib/github.js';

const SYSTEM=`Você é o agente de desenvolvimento NORTHBOUND. Trabalhe diretamente em projetos web existentes. Preserve o estilo e faça mudanças mínimas e seguras. Quando o pedido identifica claramente o alvo (ex.: "remova todos os botões relacionados ao WhatsApp"), NÃO peça confirmação: localize as ocorrências no código e execute. Só peça esclarecimento quando existirem duas interpretações realmente incompatíveis e nenhuma puder ser inferida do projeto. Nunca diga que alterou algo sem commit. Quando solicitado JSON, responda somente JSON válido.`;
function modelName(){return process.env.GEMINI_MODEL||'gemini-3.8-flash'}
function repoOf(p){return p.repository||p.config?.github||{}}
function scorePath(path,request=''){const q=String(request).toLowerCase();let s=0;if(/^(src\/)?(app|main|index)\.(tsx?|jsx?|html|css)$/.test(path.toLowerCase()))s+=8;if(/package\.json$/.test(path))s+=3;const words=[...new Set(q.normalize('NFD').replace(/[\u0300-\u036f]/g,'').match(/[a-z0-9_-]{4,}/g)||[])].filter(w=>!['remover','todos','todas','botao','botoes','alterar','mudar','quero','para','pelo','pela','relacionados'].includes(w));const pp=path.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');for(const w of words)if(pp.includes(w))s+=12;if(/src\/(components|pages|sections)\//.test(pp))s+=4;if(/\.(css|scss|sass|less)$/.test(pp))s+=3;return s}
async function contextFromRepo(token,{owner,repo,branch},request='',limit=14){const t=await getTree(token,owner,repo,branch);const paths=t.tree.filter(x=>x.type==='blob').map(x=>x.path).filter(p=>!/(^|\/)(node_modules|dist|build|\.git|public\/assets)\//.test(p)).slice(0,1200);const candidates=paths.filter(p=>/\.(tsx?|jsx?|css|scss|sass|less|html|json)$/.test(p)&&!/(package-lock|bun\.lock|yarn\.lock)/.test(p));const selected=[...candidates].sort((a,b)=>scorePath(b,request)-scorePath(a,request)).slice(0,limit);const loaded=await Promise.all(selected.map(async path=>{try{const content=await getFile(token,owner,repo,path,branch);return content.length<90000?{path,content}:null}catch{return null}}));return{paths,files:loaded.filter(Boolean)}}
function repoContextText(ctx,max=180000){return(`ÁRVORE:\n${ctx.paths.join('\n')}\n\nARQUIVOS SELECIONADOS:\n`+ctx.files.map(f=>`--- ${f.path}\n${f.content}`).join('\n')).slice(0,max)}
const LOW_THINK={thinkingConfig:{thinkingLevel:'LOW'}};

export default async function handler(req,res){if(options(req,res))return;if(req.method!=='POST')return json(res,405,{ok:false,reason:'method'});try{const p=await body(req);
if(p.op==='models')return json(res,200,{ok:true,models:[modelName()]});
if(p.op==='status')return json(res,200,{ok:true,connected:Boolean(p.connectionBlob),model:modelName(),github:null,graphify:{enabled:true,dir:'graphify-out'}});
if(p.op==='config'){if(!p.connectionBlob)return json(res,400,{ok:false,reason:'github_not_connected',msg:'Conecte o GitHub primeiro.'});const r=repoOf(p);if(!r.owner||!r.repo||!r.branch)return json(res,400,{ok:false,reason:'incomplete_github'});await getTree(tokenFromBlob(p.connectionBlob),r.owner,r.repo,r.branch);return json(res,200,{ok:true,connected:true,branch:r.branch,github:{owner:r.owner,repo:r.repo,branch:r.branch,hasToken:true},graphify:p.config?.graphify||{enabled:true,dir:'graphify-out'},model:p.config?.model||modelName()})}
if(p.op==='assistant'){const r=repoOf(p);let context='';if(p.connectionBlob&&r.owner&&r.repo&&r.branch){try{const ctx=await contextFromRepo(tokenFromBlob(p.connectionBlob),r,p.message,8);context=repoContextText(ctx,90000)}catch{}}const answer=await geminiText({system:SYSTEM,model:p.model||modelName(),generationConfig:{...LOW_THINK,maxOutputTokens:4096},prompt:`Responda de forma objetiva ao usuário sobre o projeto. Se o pedido for uma instrução de edição e o modo permitir editar, prefira executar em vez de criar obstáculos.\n\nPEDIDO:\n${p.message||''}\n\n${context}`});return json(res,200,{ok:true,pending:false,summary:answer,message:answer,sources:[]})}
if(p.op!=='agent')return json(res,400,{ok:false,reason:'unknown_op'});const action=p.action;
if(action==='improve-prompt'){const original=String(p.prompt||'').trim();if(!original)return json(res,400,{ok:false,reason:'empty_prompt',msg:'Digite um pedido primeiro.'});const text=await geminiText({system:'Você reescreve instruções para um agente de programação. Preserve exatamente a intenção e não invente requisitos.',prompt:`Reescreva o pedido abaixo para ficar claro, executável e direto. Não faça perguntas, não acrescente explicações e retorne SOMENTE o pedido melhorado.\n\n${original}`,model:p.model||modelName(),generationConfig:{...LOW_THINK,maxOutputTokens:2048}});return json(res,200,{ok:true,prompt:text,text,message:text})}
if(action==='validate-plan')return json(res,200,{ok:true,valid:true});if(action==='cancel-plan')return json(res,200,{ok:true,cancelled:true});if(['job-status','run-status','recover-run'].includes(action))return json(res,200,{ok:false,pending:false,reason:'not_found'});if(action==='analyze-attachments')return json(res,200,{ok:true,pending:false,summary:'Anexos recebidos. Posso usá-los como referência para a alteração.',message:'Anexos recebidos. Posso usá-los como referência para a alteração.'});
if(action==='plan'||action==='edit'){if(!p.connectionBlob)throw new Error('GitHub não conectado');const r=repoOf(p);if(!r.owner||!r.repo||!r.branch)throw new Error('Repositório incompleto');const token=tokenFromBlob(p.connectionBlob);const request=p.message||p.prompt||'';const ctx=await contextFromRepo(token,r,request,action==='edit'?16:10);if(action==='plan'){const plan=await geminiText({system:SYSTEM,prompt:`Crie um plano CURTO e executável. Se o alvo puder ser identificado pelo código, assuma a interpretação natural e não peça esclarecimento.\nPEDIDO:\n${request}\n\n${repoContextText(ctx,120000)}`,model:p.model||modelName(),generationConfig:{...LOW_THINK,maxOutputTokens:8192}});const id=crypto.randomUUID();return json(res,200,{ok:true,pending:false,plan,planApproval:{id,revision:1,digest:crypto.createHash('sha256').update(plan).digest('hex'),status:'pending'},text:plan,message:plan,summary:plan})}const raw=await geminiText({system:SYSTEM,model:p.model||modelName(),generationConfig:{...LOW_THINK,responseMimeType:'application/json',maxOutputTokens:65536,temperature:0.1},prompt:`Execute o pedido agora. Vasculhe os arquivos fornecidos e use a árvore para inferir o alvo. Não responda que o pedido é ambíguo quando ele nomeia um elemento, texto, serviço ou comportamento identificável. Retorne SOMENTE JSON válido: {"summary":"resumo curto do que foi feito","commitMessage":"NORTHBOUND: ...","files":[{"path":"caminho","content":"ARQUIVO COMPLETO após a alteração"}]}. Inclua apenas arquivos alterados.\n\nPEDIDO:\n${request}\n\n${repoContextText(ctx,190000)}`});const out=parseJsonLoose(raw);if(!Array.isArray(out.files)||!out.files.length)throw new Error('A IA não encontrou uma alteração concreta para aplicar. Reformule citando o elemento desejado.');for(const f of out.files){if(!f?.path||typeof f.content!=='string')throw new Error('A IA retornou alteração inválida');if(/(^|\/)(\.git|node_modules)\//.test(f.path))throw new Error('Caminho não permitido')}const commit=await commitFiles(token,{...r,files:out.files,message:out.commitMessage||'NORTHBOUND: atualização'});const summary=String(out.summary||'Alteração concluída.').trim()||'Alteração concluída.';const changes=out.files.map(f=>({path:f.path,status:'update'}));return json(res,200,{ok:true,pending:false,conversationOnly:false,summary,message:summary,commitSha:commit.sha,commitUrl:`https://github.com/${r.owner}/${r.repo}/commit/${commit.sha}`,changes,files:out.files.map(f=>f.path)})}
return json(res,400,{ok:false,reason:'unsupported_action',msg:`Ação ainda não implementada: ${action}`})}catch(e){const code=e?.code||'';if(code==='GEMINI_QUOTA')return json(res,429,{ok:false,reason:'cota_esgotada',msg:e.message});if(code==='GEMINI_TIMEOUT')return json(res,504,{ok:false,reason:'ia_demorou',msg:e.message});if(code==='EMPTY_AI_RESPONSE')return json(res,502,{ok:false,reason:'empty_ai_response',msg:e.message});return json(res,500,{ok:false,reason:'backend_error',msg:e.message})}}
